### ISSUE TITLE
It is using only a single cpu core???!

### ISSUE THREAD

**Issue by ghost** [byronknoll/lstm-compress#1]
@byronknoll 
At compression, it is using only a single cpu core, at times constantly.
This might cause the core to burn-out..

it's better to use multiple cores and threads, along with interchanging them to maintain lower heat and cpu health

**Comment by byronknoll** [comment]
Yes, it only uses a single thread. I don't think overheating is a major concern unless you are doing overclocking or have issues with cooling system. I am not a hardware expert, but I think I have seen core rotation happen automatically for single thread programs (that might be done at the OS, kernel, or hardware level). Running multiple threads at the same time would make things worse in terms of heat generation.
